apiVersion: v1
kind: Namespace
metadata:
 name: prod
 labels:
   app: spring-boot-app-prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-application-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
     app: spring-boot-app-prod
  template:
    metadata:
     labels:
       app: spring-boot-app-prod
    spec:
     nodeSelector:
       "beta.kubernetes.io/os": linux
     containers: 
     - name: spring-boot-container
       image: DOCKERUSER/spring-boot-java-web-service:BUILD_NUMBER
       resources:
         requests:
           cpu: 100m
           memory: 128Mi
         limits:
           cpu: 250m
           memory: 256Mi
       ports:
       - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: prod-service
  namespace: prod
  labels:
    app: spring-boot-app-prod
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-boot-app-prod

---

